### ISSUE TITLE
Couldn't parse loot table

### ISSUE THREAD

**Issue by NielsPilgaard** [EndlesNights/CarpetStairsMod#13]
Hi!

My log is filled with errors about loot tables from carpetstairsmod, they appear to be using blocks from mods I don't have - Would it be possible to make the loot tables only load if the relevant mod is installed? :)

**Comment by BaccarWozat** [comment]
This happened to my server, which I don't mind normally but the server freezes with no crash log, so I reverted CSM to 1.4.2 and it stopped doing this. But now it happens with Torch Slabs which I also have installed. I'm in the process of converting the modpack to Forge 31.2.0 and will see if that helps.

**Comment by EndlesNights** [comment]
As far as I'm aware there is no way to make the .json loot tables load conditionally. Which is slightly annoying. You can go into the mod .jar with a file archiver such as WinRar, navigate to data/torchslabmod/loot_talbes/blocks/ and manually delete any of the unused loot tables .json files. I'll even make it easier by adding prefixes of the other mods name IDs.

**Comment by NielsPilgaard** [comment]
I would not be allowed to distribute a jar I have changed I'm afraid, but thanks :) 
I'll just close this issue, if it's not possible to fix.
