### ISSUE TITLE
Add Waterloggable State to Wood Floors

### ISSUE THREAD

**Issue by WenXin20** [EndlesNights/CarpetStairsMod#2]
`Minecraft v1.14.4`
`Forge v28.2.0`
`Carpet Stairs v1.4`

- Wood floors cannot be waterlogged if placed on stairs that is waterloggable, so it looks odd.

- Also noticed the creative tab is missing localization. (Haven't checked v1.5 yet)

**Comment by EndlesNights** [comment]
I re uploaded the 1.14 version to quick fix the creative tab localisation. 

I will look into fixing the waterlogging issue for the wood floor, or either have them break off if the staircase/slab is water logged.
