### ISSUE TITLE
Crash on doing front and top carpet stairs

### ISSUE THREAD

**Issue by adiminut-givex** [EndlesNights/CarpetStairsMod#4]
Me and my friends use a custom modpack of around 65 mods. The mods are mainly very minimal.

**What Happened**
Attempted to place carpet on both the top and bottom of stairs. Resulted in a crash.

Here is the modlist:
[modlist.txt](https://github.com/EndlesNights/CarpetStairsMod/files/4384893/modlist.txt)

Crash report:
[crash-2020-03-26_03.38.11-server.txt](https://github.com/EndlesNights/CarpetStairsMod/files/4384894/crash-2020-03-26_03.38.11-server.txt)

Forge Version: forge-1.15.2-31.1.27
Mod Version: v1.3

Notes:
We are playing on a modded server as well encase that has any weight.

**Comment by EndlesNights** [comment]
Fixed, just had to re-compile the mod to the latest version of Forge and change a class name. Thanks for the report.

**Comment by adiminut-givex** [comment]
> 
> 
> Fixed, just had to re-compile the mod to the latest version of Forge and change a class name. Thanks for the report.

Cheers thanks
