### ISSUE TITLE
No 2nd use on carpets in certain languages

### ISSUE THREAD

**Issue by an-accident** [EndlesNights/CarpetStairsMod#6]
Carpets have only one use on stairs when game is set to language other than English(US) (or, I suppose, excluding also those mentioned in "localization support"). For example English (UK) - Aprils Fools varsion or Polish (my 1st) aren't working - carpets can't be switched to "cover front" state.
I would suggest fixing it the proper way, but anyway here are polish names for carpets:
white: "Biały dywan"
orange: "Pomarańczowy dywan"
magenta: "Karmazynowy dywan"
l.blue: 'Jasnoniebieski dywan"
yellow: "Żółty dywan"
lime: "Jasnozielony dywan"
pink: "Różowy dywan"
grey: "Szary dywan"
l.grey: "Jasnoszary dywan"
cyan: "Błękitny dywan"
purple: "Fioletowy dywan"
blue: "Niebieski dywan"
brown: "Brązowy dywan"
green: "Zielony dywan"
red: "Czerwony dywan"
black: "Czarny dywan"
And, for full localization, here are names for floorings, translated in the same convention as other wooden things:
accacia floor: "Akacjowa podłoga"
birch: "Brzozowa podłoga"
jungle: "Tropikalna podłoga"
spruce: "Świerkowa podłoga"
oak: "Dębowa podłoga"
dark oak: "Ciemnodębowa podłoga"

**Comment by EndlesNights** [comment]
Fixed the issue the proper way, and removed the hacky bit of code. No idea why I even did it that way in the first place. Thanks for brining this to my attention. I'll see about adding more localisation support some time soonish™.
