### ISSUE TITLE
Server crash when placing carpet on carpet

### ISSUE THREAD

**Issue by DasFantatier** [EndlesNights/CarpetStairsMod#7]
We get a server crash when we try to place carpet on carpet.
I tried it 2 more times to test, it happens every time.

Here is the error report:
https://pastebin.com/dzva9Uib

We use MC 1.15.2 with Forge 31.1.0

**Comment by EndlesNights** [comment]
Just judging by the error message, you might want to double check that your client and the server are both running the same version of the mod. I'd recommend just downloading the latest version here: https://www.curseforge.com/minecraft/mc-mods/carpet-stairs-mod/files/2918839

**Comment by DasFantatier** [comment]
Seems we just installed this mod right before the update, so we had the version before.
Now it works perfectly fine with the new update!

Thank you - closed

**Comment by DasFantatier** [comment]
Damn, now there was another error, just going to open a new issue.
