### ISSUE TITLE
Error placing carpet on carpet

### ISSUE THREAD

**Issue by DasFantatier** [EndlesNights/CarpetStairsMod#8]
Crash Report:
https://pastebin.com/uy7Lcaic

I just updated the Mod to the latest version and got the error again.
I get the error always when trying to place a carpet on a carpet, no matter if wooden or wool.
Normally it´s not on purpose to place a carpet on a carpet, but i have to restart the server if someone klicks wrong by mistake.

Minecraft 1.15.2, Forge 31.1.0, Carpet Mod 1.4.1
![Screen Shot 04-03-20 at 02 42 PM](https://user-images.githubusercontent.com/62701156/78361904-73c65a00-75b9-11ea-9726-e31784909921.PNG)
![Screen Shot 04-03-20 at 02 42 PM 001](https://user-images.githubusercontent.com/62701156/78361907-745ef080-75b9-11ea-860a-14d94df11736.PNG)

**Comment by EndlesNights** [comment]
So I was unable to reproduce the same crash results on my own server in either Forge 31.1.0 or Forge 31.1.24, but I rewrote the line that section that was causing the crash for you. Other than that, be sure that both your server and clients are up to date. And let me know if  this hotfix works for you. Sorry for any inconveniences to your server.

[carpetstairsmod-1.4.2.0 HOTFIX.zip](https://github.com/EndlesNights/CarpetStairsMod/files/4428872/carpetstairsmod-1.4.2.0.HOTFIX.zip)

**Comment by DasFantatier** [comment]
@EndlesNights  thank you very much, it seems the hotfix is working fine, i installed it on server only.
No more crashes now when placing a carpet on a carpet :)
